export type {
  AuthMethod,
  DatabaseDialect,
  MaitreType,
  ConnectionConfig,
  PoolConfig,
  StreamOptions,
  ConnectionTestResult,
  Connection,
  FieldInfo,
  QueryResult,
  SchemaInfo,
  TableInfo,
  ColumnInfo,
  IndexInfo,
  FunctionInfo,
  ProcedureInfo,
  TypeInfo,
  RoleInfo,
  GrantInfo,
  ExplainOptions,
  ExplainResult,
  PlanNode,
  TransactionOptions,
  Transaction,
  DriverCapabilities,
  SslOptions,
  TunnelConfig,
  DriverOptions,
  SqliteOptions,
  PostgresOptions,
  MysqlOptions,
  SnowflakeOptions,
  MongoOptions,
  ClickHouseOptions,
  DuckDbOptions,
  BigQueryOptions,
  RedshiftOptions,
  AthenaOptions,
} from './types.js';

export type { DriverAdapter } from './driver-adapter.js';

export { PluginRegistry } from './registry.js';
